name: 'ArgoCD PR Jsonnet Application'
description: 'Deploy argocd application running jsonnet compiled manifests'
inputs:
  github-pat:
    description: 'secrets.GITHUB_PAT'
    required: true
  org:
    description: 'github orginization'
    required: true
  infra-repo:
    description: 'infra repo name'
    required: true
  pr-ref:
    description: 'github.event.pull_request.head.ref'
    required: true
  cluster:
    description: 'github.event.deployment.environment'
    required: true
  domain:
    description: 'domain name for the compiled application'
    required: true
  image:
    description: 'docker image name for the compiled application manifests'
    required: true
  tag:
    description: 'docker image tag for the compiled application manifets'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  args:
    - ${{ inputs.github-pat }}
    - ${{ inputs.org }}
    - ${{ inputs.infra-repo}}
    - ${{ inputs.pr-ref }}
    - ${{ inputs.cluster }}
    - ${{ inputs.domain }}
    - ${{ inputs.image }}
    - ${{ inputs.tag }}
