name: 'ArgoCD PR Jsonnet Application'
description: 'Deploy argocd application running jsonnet compiled manifests'
inputs:
  github-pat:
    description: 'secrets.GITHUB_PAT'
    required: true
  org:
    description: 'github orginization'
    required: true
  infra-repo:
    description: 'infra repo name'
    required: true
  pr-ref:
    description: 'github.event.pull_request.head.ref'
    required: true
  image:
    description: 'docker image name for the compiled application manifests'
    required: true
  tag:
    description: 'docker image tag for the compiled application manifets'
    required: true
  aws_access_key_id:
    description: 'AWS_ACCESS_KEY_ID'
    required: true
  aws_secret_access_key:
    description: 'AWS_SECRET_ACCESS_KEY'
    required: true
  aws_default_region:
    description: 'AWS_DEFAULT_REGION'
    required: true
  aws_org_id:
    description: 'AWS_ORG_ID'
    required: true
  aws_eks_cluster_name:
    description: 'AWS_EKS_CLUSTER_NAME'
    required: true         
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github-pat }}
    - ${{ inputs.org }}
    - ${{ inputs.infra-repo}}
    - ${{ inputs.pr-ref }}
    - ${{ inputs.image }}
    - ${{ inputs.tag }}
    - ${{ inputs.aws_access_key_id }}
    - ${{ inputs.aws_secret_access_key }}
    - ${{ inputs.aws_default_region }}
    - ${{ inputs.aws_org_id }}
    - ${{ inputs.aws_eks_cluster_name }}

    GITHUB_PAT=${1}
ORG=${2}
INFRA_REPO=${3}
PR_REF=${4}
IMAGE=${5}
SHA=${6}
AWS_ACCESS_KEY_ID=${7}
AWS_SECRET_ACCESS_KEY=${8}
AWS_DEFAULT_REGION=${9}
AWS_ORG_ID=${10}
AWS_EKS_CLUSTER_NAME=${11}